name: aoc
description: "Solutions to Advent of Code problems"
version: 0.0.1

environment:
  sdk: ">=3.5.2"

dependencies:
  args: ^2.5.0
  collection: ^1.19.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.8
