name: aoc
description: Advent of Code solutions in Dart from the years 2015-2021
version: 0.0.1

environment:
  sdk: ">=3.2.3"

dependencies:
  args: ^2.4.2
  collection: ^1.18.0
  crypto: ^3.0.3
  dart_scope_functions: ^0.1.4

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.0
