name: aoc
description: "Solutions to Advent of Code problems in Dart"
version: 0.0.1

environment:
  sdk: ">=3.5.4"

dependencies:
  args: ^2.6.0
  collection: ^1.19.1
  crypto: ^3.0.6

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.8
